---
elk_java:
  flavor: openjdk
  oracle:
    - oracle-java8-installer
    - oracle-java8-set-default
  openjdk:
    - openjdk-8-jre-headless

elk_elasticsearch:
  version: 6.x
  pid_file: /var/run/elasticsearch.pid
  http:
    port: 9200

elk_logstash:
  version: 6.x
  pid_file: /var/run/logstash.pid
  configs:
    - { src: logstash-simple.conf.j2, dest: simple.conf }
  patterns: [] # optional; follows same format as `configs`

elk_kibana:
  version: 6.2.3-linux-x86_64
  path: /opt/kibana
  port: 5601
  user: kibana # optional; if unset, kibana does not require authentication
  password: kibana # optional; if unset, kibana does not require authentication
  allowed_addresses:
    - 127.0.0.1

elk_nginx:
  port: 80
  user: nginx
